import type { CardData } from './types'

const today = new Date().toISOString().slice(0, 10)

export const emptyData: CardData = {
  inventory: [],
  purchases: [],
  sales: [],
  grading: [],
  expenses: [],
  feePresets: [],
  importBatches: [],
}

export const sampleData: CardData = {
  inventory: [
    {
      id: 'demo-inv-1',
      item_id: 'DEMO-PKM-001',
      lot_id: 'DEMO-LOT-001',
      game: 'Pokemon',
      product_type: 'Slab',
      name: 'Demo Pikachu Full Art',
      subject: 'Pikachu',
      year: '2024',
      set_name: 'Demo Set',
      card_number: '101',
      condition: 'PSA 10',
      grading_company: 'PSA',
      grade: '10',
      cert_number: 'DEMO-CERT-001',
      qty_acquired: 1,
      base_unit_cost: 420,
      manual_market_value: 565,
      market_value_date: today,
      status: 'Active',
      notes: 'Safe demo record. Replace through CSV Import or Supabase data.',
    },
    {
      id: 'demo-inv-2',
      item_id: 'DEMO-OP-001',
      lot_id: 'DEMO-LOT-002',
      game: 'One Piece',
      product_type: 'Raw Single',
      name: 'Demo Leader Parallel',
      subject: 'Leader',
      year: '2025',
      set_name: 'Demo Romance Dawn',
      card_number: 'L-001',
      condition: 'Near Mint',
      qty_acquired: 2,
      base_unit_cost: 65,
      manual_market_value: 88,
      market_value_date: today,
      status: 'Active',
      notes: 'Safe demo row used when Supabase is not configured.',
    },
    {
      id: 'demo-inv-3',
      item_id: 'DEMO-BOX-001',
      lot_id: 'DEMO-LOT-003',
      game: 'Pokemon',
      product_type: 'Sealed',
      name: 'Demo Booster Box',
      year: '2025',
      set_name: 'Demo Expansion',
      condition: 'Sealed',
      qty_acquired: 3,
      base_unit_cost: 94,
      manual_market_value: 118,
      market_value_date: today,
      status: 'Active',
      notes: 'Sealed inventory example.',
    },
  ],
  purchases: [
    {
      id: 'demo-purchase-1',
      lot_id: 'DEMO-LOT-001',
      purchase_date: today,
      seller: 'Demo Seller',
      source: 'Card show',
      total_paid: 420,
      tax: 0,
      shipping: 0,
      allocated_cost: 420,
      payment_method: 'Cash',
      notes: 'Example purchase lot.',
    },
    {
      id: 'demo-purchase-2',
      lot_id: 'DEMO-LOT-002',
      purchase_date: today,
      seller: 'Demo Marketplace',
      source: 'Online',
      total_paid: 130,
      tax: 8,
      shipping: 6,
      allocated_cost: 144,
      payment_method: 'Credit Card',
      notes: 'Example purchase lot.',
    },
  ],
  sales: [
    {
      id: 'demo-sale-1',
      sale_date: today,
      channel: 'eBay',
      item_id: 'DEMO-OP-001',
      quantity: 1,
      gross_sale: 112,
      shipping_charged: 5,
      fee_rate: 0.1325,
      fee_flat: 0.4,
      fees_override: null,
      shipping_cost: 4.25,
      supplies_cost: 0.75,
      status: 'Delivered',
      notes: 'Example sale with default channel fees.',
    },
  ],
  grading: [
    {
      id: 'demo-grade-1',
      submission_id: 'DEMO-SUB-001',
      item_id: 'DEMO-PKM-001',
      company: 'PSA',
      submission_date: today,
      returned_date: today,
      grading_fee: 25,
      shipping_fee: 5,
      grade_result: '10',
      cert_number: 'DEMO-CERT-001',
      status: 'Complete',
      notes: 'Example grading allocation.',
    },
  ],
  expenses: [
    {
      id: 'demo-expense-1',
      expense_date: today,
      category: 'Supplies',
      vendor: 'Demo Supplies',
      amount: 18.5,
      payment_method: 'Credit Card',
      notes: 'Top loaders and team bags.',
    },
  ],
  feePresets: [
    { id: 'preset-1', channel: 'eBay', fee_rate: 0.1325, fee_flat: 0.4, notes: 'Default trading card estimate.' },
    { id: 'preset-2', channel: 'Whatnot', fee_rate: 0.11, fee_flat: 0.3, notes: 'Marketplace and payment estimate.' },
    { id: 'preset-3', channel: 'Card Show', fee_rate: 0, fee_flat: 0, notes: 'Cash sale preset.' },
  ],
  importBatches: [],
}
